name: default

kind: pipeline
type: docker

steps:
- name: backend
  image: golang
  commands:
    - go build
    - go test

- name: docker  
  image: plugins/docker
  settings:
    repo: thomaslacaze/peace-api
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password