name: default

kind: pipeline
type: docker

steps:
- name: test
  image: golang
  commands:
    - go test
- name: build
  image: golang
  commands:
    - go build

- name: docker  
  image: plugins/docker
  settings:
    repo: thomaslacaze/peace-api
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password