name: default

kind: pipeline
type: docker

steps:
#- name: test
#  image: golang
#  commands:
#    - go test

- name: build
  image: golang
  commands:
    - go build

- name: push dockerhub  
  image: plugins/docker
  settings:
    repo: thomaslacaze/peace-api
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - main

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 
       from_secret: ssh_host 
    username: 
        from_secret: ssh_username
    password: 
        from_secret: ssh_password
    port: 
        from_secret: ssh_port
    script:
      - docker pull thomaslacaze/peace-api
      - cd /root/mailcow-dockerized && docker-compose up -d peaceland
    when:
      branch:
      - main